### ISSUE TITLE
No CTP data   #CTP

### ISSUE THREAD

**Issue by iamvernon** [xcedertechnology/Xceder#1]
Testing  *\*   there are 0 prices coming from the CTP data. nothing was display when i was fetching the information from the CTP.   e.g AU1606

**Comment by dreamershl** [comment]
The data is from orient futures server. Will check with them on the data issue. 

And also need pay attention to the trading hour. In non trading hour, there is no price too.

normal 9:00AM-11:30AM, 1:30PM-3:00PM
                      AU 9:00PM-2:30AM, i 9PM-11:30PM

**Comment by dreamershl** [comment]
In CTP demo server, the price is from other players in the demo server. when there is no other quote on the counter, the price won't be there too.
